# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import logistics_pb2 as logistics__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in logistics_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LogisticsMonitorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubscribeTransport = channel.unary_stream(
                '/logistics.LogisticsMonitor/SubscribeTransport',
                request_serializer=logistics__pb2.SubscriptionRequest.SerializeToString,
                response_deserializer=logistics__pb2.TransportEvent.FromString,
                _registered_method=True)
        self.UnsubscribeTransport = channel.unary_unary(
                '/logistics.LogisticsMonitor/UnsubscribeTransport',
                request_serializer=logistics__pb2.UnsubscribeRequest.SerializeToString,
                response_deserializer=logistics__pb2.UnsubscribeResponse.FromString,
                _registered_method=True)


class LogisticsMonitorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubscribeTransport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnsubscribeTransport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LogisticsMonitorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubscribeTransport': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeTransport,
                    request_deserializer=logistics__pb2.SubscriptionRequest.FromString,
                    response_serializer=logistics__pb2.TransportEvent.SerializeToString,
            ),
            'UnsubscribeTransport': grpc.unary_unary_rpc_method_handler(
                    servicer.UnsubscribeTransport,
                    request_deserializer=logistics__pb2.UnsubscribeRequest.FromString,
                    response_serializer=logistics__pb2.UnsubscribeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'logistics.LogisticsMonitor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('logistics.LogisticsMonitor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LogisticsMonitor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubscribeTransport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/logistics.LogisticsMonitor/SubscribeTransport',
            logistics__pb2.SubscriptionRequest.SerializeToString,
            logistics__pb2.TransportEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnsubscribeTransport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/logistics.LogisticsMonitor/UnsubscribeTransport',
            logistics__pb2.UnsubscribeRequest.SerializeToString,
            logistics__pb2.UnsubscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
