# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: logistics.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'logistics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0flogistics.proto\x12\tlogistics\"P\n\x08Location\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\x12\x0c\n\x04\x63ity\x18\x03 \x01(\t\x12\x11\n\tarea_code\x18\x04 \x01(\t\"\x82\x01\n\x13SubscriptionRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x17\n\x0fsubscription_id\x18\x02 \x01(\t\x12+\n\x0btype_filter\x18\x03 \x01(\x0e\x32\x16.logistics.VehicleType\x12\x12\n\narea_codes\x18\x04 \x03(\t\"@\n\x12UnsubscribeRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x17\n\x0fsubscription_id\x18\x02 \x01(\t\"7\n\x13UnsubscribeResponse\x12\x0f\n\x07removed\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x97\x02\n\x0eTransportEvent\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x13\n\x0bshipment_id\x18\x02 \x01(\t\x12\'\n\x07vehicle\x18\x03 \x01(\x0e\x32\x16.logistics.VehicleType\x12-\n\x10\x63urrent_location\x18\x04 \x01(\x0b\x32\x13.logistics.Location\x12\x16\n\x0estatus_history\x18\x05 \x03(\t\x12\x17\n\x0f\x65vent_unix_time\x18\x06 \x01(\x03\x12\x16\n\x0c\x64\x65lay_reason\x18\x07 \x01(\tH\x00\x12\x1a\n\x10sensor_threshold\x18\x08 \x01(\x05H\x00\x12\x18\n\x0esecurity_alert\x18\t \x01(\tH\x00\x42\x07\n\x05\x61lert*N\n\x0bVehicleType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x10\n\x0c\x44\x45LIVERY_VAN\x10\x01\x12\x0f\n\x0bHEAVY_TRUCK\x10\x02\x12\x0f\n\x0b\x43\x41RGO_PLANE\x10\x03\x32\xbc\x01\n\x10LogisticsMonitor\x12Q\n\x12SubscribeTransport\x12\x1e.logistics.SubscriptionRequest\x1a\x19.logistics.TransportEvent0\x01\x12U\n\x14UnsubscribeTransport\x12\x1d.logistics.UnsubscribeRequest\x1a\x1e.logistics.UnsubscribeResponseB\x1f\n\x0bsr.grpc.genB\x0eLogisticsProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'logistics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013sr.grpc.genB\016LogisticsProtoP\001'
  _globals['_VEHICLETYPE']._serialized_start=650
  _globals['_VEHICLETYPE']._serialized_end=728
  _globals['_LOCATION']._serialized_start=30
  _globals['_LOCATION']._serialized_end=110
  _globals['_SUBSCRIPTIONREQUEST']._serialized_start=113
  _globals['_SUBSCRIPTIONREQUEST']._serialized_end=243
  _globals['_UNSUBSCRIBEREQUEST']._serialized_start=245
  _globals['_UNSUBSCRIBEREQUEST']._serialized_end=309
  _globals['_UNSUBSCRIBERESPONSE']._serialized_start=311
  _globals['_UNSUBSCRIBERESPONSE']._serialized_end=366
  _globals['_TRANSPORTEVENT']._serialized_start=369
  _globals['_TRANSPORTEVENT']._serialized_end=648
  _globals['_LOGISTICSMONITOR']._serialized_start=731
  _globals['_LOGISTICSMONITOR']._serialized_end=919
# @@protoc_insertion_point(module_scope)
